app/staff/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectMultipleField, TextAreaField, HiddenField, SelectField
from wtforms.validators import DataRequired, Optional


class ProfileForm(FlaskForm):
    email = StringField('Email', render_kw={'disabled':''}, validators=[DataRequired()])
    username = StringField('Username', render_kw={'disabled':''}, validators=[DataRequired()])
    first_name = StringField('First name', render_kw={'disabled':''}, validators=[DataRequired()])
    last_name = StringField('Last name', render_kw={'disabled':''}, validators=[DataRequired()])
    profile_comment = TextAreaField('Profile comment')
    submit = SubmitField('Save')


class ProjectForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    academic_year = SelectField('Academic year')
    overview = TextAreaField('Overview', validators=[DataRequired()])
    deliverables = TextAreaField('Deliverables', validators=[DataRequired()])
    resources = TextAreaField('Resources', validators=[DataRequired()])
    skills_required = SelectMultipleField('Skills required', coerce=int)
    submit = SubmitField('Save')

app/staff/__init__.py
from flask import Blueprint

staff = Blueprint('staff', __name__)

from . import views

app/staff/views.py
from flask import render_template, flash, redirect, url_for, request, abort
from flask_login import current_user, login_required
from collections import Counter, OrderedDict

from sqlalchemy import and_, or_, text

from . import staff
from .forms import *
from app.models import *
from app.common import *
import logging
logger = logging.getLogger()


@staff.route('/staff/projects')
@login_required
def projects():
    skill = request.args.get("skill")
    company = request.args.get("company")
    projects = Project.query.order_by((Project.client_id == current_user.id).desc()).order_by(Project.academic_year.desc(), Project.title)
    academic_years = [y.year for y in AcademicYear.query.order_by(text('start_date'))]
    academic_year = session['academic_year']

    # ToDo: Modify the dropdowns to show the correct values wen the projects are filtered
    skills = []
    bids = {}
    for project in projects:
        bids[project.id] = len(get_bids(project))
        skills += [(s.skill_required.name, s.skill_required.name) for s in project.skills_required]
    skills = sorted(Counter(skills).items(), key=lambda x: x[0][0].lower())

    companies = []
    companies += [(p.client.company.name, p.client.company.name) for p in projects if p.client.company_id is not None]
    companies = sorted(Counter(companies).items(), key=lambda x: x[0][0].lower())
    return render_template('staff/projects/projects.html',
                           academic_year=academic_year,
                           academic_years=academic_years,
                           projects=projects,
                           bids=bids,
                           skills=skills,
                           skill=skill,
                           companies=companies,
                           company=company,
                           title="Projects")


@staff.route('/staff/my_projects')
@login_required
def my_projects():
    projects = Project.query.filter(Project.client_id == current_user.id).all()
    bids={}
    for project in projects:
        bids[project.id] = len(get_bids(project))
    from_statuses = [p.status_id for p in projects]
    transitions = Transition.query.filter(Transition.from_status_id.in_(from_statuses), Transition.admin_only == False).all()
    return render_template('staff/projects/my_projects.html',
                           projects=projects,
                           bids=bids,
                           academic_year = get_this_year(),
                           transitions=transitions,
                           title="My projects")


@staff.route('/staff/add_project', methods=['GET', 'POST'])
@login_required
def add_project():
    add_project = True

    form = ProjectForm()
    form.skills_required.choices = [(s.id, s.name) for s in Skill.query.order_by(text('name'))]
    project_domain = Domain.query.filter(Domain.name == 'project').first()
    default_status = Status.query.filter(Status.domain_id == project_domain.id,
                                         Status.default_for_domain == True).first()
    form.academic_year.choices = [(y.year, y.year) for y in AcademicYear.query.filter(AcademicYear.end_date > datetime.now()).order_by(text('start_date'))]

    if form.validate_on_submit():
        skills_required = form.skills_required.data
        project = Project(title = form.title.data,
                          client_id = current_user.id,
                          overview = form.overview.data,
                          deliverables = form.deliverables.data,
                          resources = form.resources.data,
                          academic_year = form.academic_year.data,
                          status_id = default_status.id)

        try:
            db.session.add(project)
            db.session.commit()
            db.session.refresh(project)
            if project.id:
                for skill in skills_required:
                    skill_required = SkillRequired(project_id=project.id, skill_id=skill)
                    db.session.add(skill_required)
                db.session.commit()
                logger.info('NEW STAFF PROJECT: {:d}, {}, {:d}'.format(project.id, project.title, project.client_id))
                flash('You have successfully added a new project.')
                return redirect(url_for('staff.projects'))
            else:
                raise RuntimeError

        except RuntimeError:
            flash('An unknown problem occurred while trying to save a new project', 'error')
            logger.error('PROJECT INSERT ERROR: {:d}, {}'.format(project.client_id, project.title))
        except:
            flash('There was a problem saving your project', 'error')

    return render_template('staff/projects/edit_project.html', add_project=add_project,
                           form=form, title='Add project')


@staff.route('/staff/profile/edit', methods=['GET', 'POST'])
@login_required
def profile():
    user = User.query.get(current_user.id)
    form = ProfileForm(obj=user)

    if form.validate_on_submit():
        user.profile_comment = form.profile_comment.data
        db.session.commit()
        flash('Profile updated')
        return redirect(url_for('staff.projects'))

    if form.errors:
        for field in form.errors:
            for error in form.errors[field]:
                flash(error, 'error')

    return render_template('staff/profile/profile.html', user=user, form=form, title="Edit profile")


@staff.route('/staff/project/<int:id>')
@login_required
def project(id):
    project = Project.query.get(id)
    interest = Interest.query.filter(and_(Interest.project_id == id, Interest.user_id == current_user.id)).first()
    flag = Flag.query.filter(and_(Flag.project_id == id, Flag.user_id == current_user.id)).first()
    teams = Team.query.filter(Team.project_id == id)
    team_member = TeamMember.query.filter(and_(TeamMember.user_id == current_user.id,
                                               TeamMember.team_id.in_([t.id for t in teams]))).first()
    return render_template('staff/projects/project.html',
                           project=project,
                           interest=interest,
                           flag=flag,
                           team_member=team_member,
                           title='View project')



@staff.route('/staff/edit_project/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_project(id):
    add_project = False

    project = Project.query.get_or_404(id)
    check_client(project)

    form = ProjectForm(obj=project)
    form.academic_year.choices = [(y.year, y.year) for y in AcademicYear.query.order_by(text('start_date'))]
    form.skills_required.choices = [(s.id, s.name) for s in Skill.query.order_by(text('name'))]
    form.skills_required.data = [s.skill_id for s in project.skills_required]
    if form.validate_on_submit():
        project.title = form.title.data
        project.overview = form.overview.data
        project.deliverables = form.deliverables.data
        project.resources = form.resources.data
        project.academic_year = form.academic_year.data
        project.updated_date = datetime.now()
        db.session.add(project)
        SkillRequired.query.filter(SkillRequired.project_id==project.id).delete()
        for skill in form.skills_required.raw_data:
            if skill not in [s.skill_id for s in project.skills_required]:
                skill_required = SkillRequired(project_id=project.id, skill_id=skill)
                db.session.add(skill_required)
        db.session.commit()
        flash('You have successfully edited the project.')

        return redirect(url_for('staff.projects'))

    return render_template('staff/projects/edit_project.html', add_project=add_project,
                           project=project, form=form, title="Edit project")


@staff.route('/staff/project/<int:id>/duplicate')
@login_required
def duplicate(id):
    old_project = Project.query.get_or_404(id)
    check_client(old_project)

    new_project = Project(
        title = old_project.title,
        client_id = current_user.id,
        academic_year = get_this_year().year,
        overview = old_project.overview,
        deliverables = old_project.deliverables,
        resources = old_project.resources,
        status_id = get_status('project', 'New').id
    )

    db.session.add(new_project)
    db.session.commit()
    db.session.refresh(new_project)

    for skill in old_project.skills_required:
        db.session.add(SkillRequired(project_id=new_project.id, skill_id=skill.skill_id))
    db.session.commit()

    return redirect(url_for('staff.my_projects'))


#--------  Bid management ----------#


@staff.route('/staff/bids/<int:id>', methods=['GET', 'POST'])
@login_required
def bids(id):

    project = Project.query.get_or_404(id)
    check_client(project)
    bids = get_bids(project)
    from_statuses = [t.status_id for t in project.teams]
    domain = Domain.query.filter(Domain.name == 'team').first()
    shortlisted = Status.query.filter(and_(Status.domain==domain, Status.name=='Shortlisted')).first()
    shortlist = False
    if shortlisted.id in from_statuses:
        shortlist = True
    settings = Settings.query.first()

    transitions = Transition.query.filter(Transition.from_status_id.in_(from_statuses), Transition.admin_only == False).all()

    return render_template('staff/bids/bids.html',
                           project=project,
                           bids=bids,
                           shortlist=shortlist,
                           transitions=transitions,
                           settings=settings,
                           title="Bids")


@staff.route('/staff/bids/transition/<int:id>/<int:status_id>', methods=['GET', 'POST'])
@login_required
def bid_transition(id, status_id):

    team = Team.query.get_or_404(id)
    check_client(team.project)

    status = Status.query.get(status_id)
    team.status_id = status.id
    accepted = get_status('team', 'Accepted')

app/templates/staff/projects/edit_project.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_project %}
        Add Project
    {% else %}
        Edit Project
    {% endif %}
{% endblock %}

{% block content %}
    {{  super() }}
    <div class="content-section">
     <div class="outer">
        <div class="middle">
          <div class="inner">
            <div class="center">
                {% if add_project %}
                    <h1>Add Project</h1>
                {% else %}
                    <h1>Edit Project</h1>
                {% endif %}
                <br/>
                {{ wtf.quick_form(form) }}
                {%  if not add_project %}
                    <div id="date_info">
                    Created: {{ project.created_date }}<br/>
                    Last updated: {{ project.updated_date }}
                    </div>
                {%  endif %}
            </div>
          </div>
        </div>
      </div>
    {% block footer %} {{  super() }} {% endblock footer%}
    </div>
{% endblock content%}
{% block help %}
    <p>There are six pieces of information required in a project brief:</p>
    <ul>
    <li>The <em>Title</em> is a one-line summary of the project used to identify the project easily.</li>
    <li>The <em>Academic year</em> is selected from a drop-down list.</li>
    <li>The <em>Overview</em> is a longer description of the project. Students rely on this to form their ideas about
        what the project involves. This section should include the goals, type of activity and the technology to be
        used (if known). You should also highlight the attractive features of the project here.
    </li>
    <li>The <em>Deliverables</em> section lists the expected results from the project. Here, it is good to be specific:
        if you are expecting a piece of software that should be clearly stated. Other deliverables could include reports,
        design documentation, graphical assets, etc.
    </li>
    <li>The <em>Resources available</em> is another list, this time detailing what you can provide to the team to help
        get the work done. This varies enormously from one project to another, and could include software or hardware
        resources, workspace, documentation, etc. It is also a good idea to be specific about how much of your time
        the students can expect to benefit from.
    </li>
    <li>The <em>Skills required</em> section lets you choose skills from a list. To pick more than one, use CTRL-Click
        on a PC and Command-Click on a Mac. If you do not have a clear idea of the skills your project may require,
        just choose something generic and a member of academic staff will be able to suggest something more specific.
    </li>
    </ul>
    <p>Once your project brief has been saved, it will be reviewed by a member of academic staff who will discuss any
    issues with you. Changes may be needed, for example, if the scope of the project is too broad, or if there is
    anything that the students may not understand clearly. Staff have extensive experience of preparing instructions
    for students and are in a good position to help make your project brief accessible.
    </p>
    <p>
    After your project is submitted, it is not immediately visible to students. This is to allow an opportunity to
    discuss the details and make any amendments that may be needed.
    </p>
{% endblock %}

app/templates/staff/projects/my_projects.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% import 'macros.html' as m %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <div class="center">
                    <br/>
                    {% if projects %}
                        <div class="card">
                            <div class="card-header">
                            <ul class="nav nav-tabs card-header-tabs">
                            {% for project in projects %}
                                  <li class="nav-item">
                                    <a class="nav-link active" id="{{ project.id }}-tab" data-toggle="tab" href="#{{ project.id }}"
                                       role="tab" aria-controls="home" aria-selected="true" aria-expanded="true">Project {{ loop.index }}</a>
                                  </li>
                            {% endfor %}
                            </ul>
                            </div>
                            <div class="card-body">
                                <div class="tab-content" id="myTabContent">
                                    {% for project in projects %}
                                        {% if loop.first %}
                                            <div class="tab-pane fade active in" id="{{project.id}}" role="tabpanel" aria-labelledby="{{project.id}}-tab">
                                        {% else %}
                                            <div class="tab-pane fade" id="{{project.id}}" role="tabpanel" aria-labelledby="{{project.id}}-tab">
                                        {% endif %}

                                            <h4>{{ project.title }}</h4>
                                            <p class="info-text">Academic year: {{ project.academic_year }}      Created: {{ project.created_date }}</p>
                                            <p><span class="badge {{ project.status.name }}">{{ project.status.name }}</span>: {{ project.status.description }}</p>
                                            <h5>Overview </h5>
                                            <p class="preserve_newlines">{{ project.overview }}</p>
                                            <h5>Deliverables </h5>
                                            <p class="preserve_newlines">{{ project.deliverables }}</p>
                                            <h5>Resources </h5>
                                            <p class="preserve_newlines">{{ project.resources }}</p>
                                            <h5>Skills required </h5>
                                                {% for skill in project.skills_required %}
                                                    {{ skill.skill_required.name }}<br/>
                                                {%  endfor %}

                                            <br/><br/>

                                            {% if project.status.name != 'Complete' %}
                                                {% if bids[project.id] > 0 %}
                                                    <a href="{{ url_for('staff.bids', id=project.id) }}" class="btn btn-default">
                                                        {% if project.status.name == 'Taken' %}
                                                            {% if bids[project.id] > 1 %}
                                                                Teams
                                                            {% else %}
                                                                Team
                                                            {% endif %}
                                                        {% else %}
                                                            Bids <span class="badge badge-info">{{ bids[project.id] }}</span>
                                                        {% endif %}
                                                    </a>
                                                {% else %}
                                                    <button type="button" class="btn btn-default disabled">
                                                        Bids</span>
                                                    </button>
                                                {% endif %}
                                                <a href="{{url_for('staff.edit_project', id=project.id) }}" class="btn btn-default">Edit</a>
                                            {% endif %}
                                            {% for transition in transitions %}
                                                {% if transition.from_status_id == project.status_id %}
                                                    {{ m.status('project', 'staff.bid_transition', project.id, transition)}}
                                                {% endif %}
                                            {% endfor %}
                                            {% if project.status.name == 'Old' %}
                                                <a href="{{ url_for('staff.duplicate', id=project.id) }}" class="btn btn-default">
                                                    Copy for {{ academic_year.year }}
                                                </a>
                                            {% endif %}
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% else %}
                      <div style="text-align: center">
                        <h4> You have no projects yet.<br/><br/>You can add a new one using the 'New Project' link in the menu. </h4>
                        <hr class="intro-divider">
                    {% endif %}
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
    {% block footer %} {{  super() }} {% endblock footer%}
{% endblock %}
{% block help %}
    <p>
        This page gives you access to all of the features you need to manage your projects which are visible in the
        central tabbed area.
    </p>
    <p>
        The menu items are self-explanatory and lead to other pages where further help information is available.
    </p>
        The <em>Bids</em> button shows how many teams are bidding on each project. Clicking it takes you to a page where
        you can see the details of the bids and respond to them.
    </p>
    <p>
        The other buttons below a project let you change its status. The available statuses are listed below:
        <ul>
            <li><em>New</em>: The project is being checked by academic staff and is not yet visible to the students.</li>
            <li><em>Live</em>: The project is visible to the students and teams can make bids.
                A project can only be moved to <em>Live</em> by a member of academic staff. Another requirement is
                that you have completed your profile.
            </li>
            <li><em>Protected</em>: A project in this status is only visible to selected students. This can be used,
                for example, when you have already decided on a team and you do not wish the project to be available
                for other bids.
            </li>
            <li><em>Withdrawn</em>: A project in this status is no longer visible to students. This would be appropriate,
                for example, when you change your mind or a project is no longer viable.
            </li>
            <li><em>Relisted</em>: A <em>Withdrawn</em> project can be relisted. This status requires checking by a member of
                academic staff just like a <em>New</em> project.
            </li>
            <li><em>Complete</em>: Once the project is over and you have taken delivery of the results,
                the project's status should be updated to <em>Complete</em>.
            </li>

        </ul>
    </p>
{% endblock %}

app/templates/staff/projects/projects.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                <div class="container projects">
                    <div>
                        <select id="year-filter">
                            {% for year in academic_years %}
                                {% if year == academic_year %}
                                    <option value="{{ year }}" selected="selected">{{ year }}</option>
                                {% else %}
                                    <option value="{{ year }}">{{ year }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                        {% if skill %}
                            {{ skill }}
                        {% else %}
                            <select id="skill-filter">
                                <option value="0">Filter by skill</option>
                                {% for option, count in skills %}
                                    <option value="{{ option[1] }}">{{ option[0] }} ({{ count }})</option>
                                {% endfor %}
                            </select>
                        {% endif %}
                        {% if company %}
                            {{ company }}
                        {% else %}
                            <select id="company-filter">
                                <option value="0">Filter by company</option>
                                {% for option, count in companies %}
                                    <option value="{{ option[1] }}">{{ option[0] }} ({{ count }})</option>
                                {% endfor %}
                            </select>
                        {% endif %}
                    </div>
                    <div class="card-deck">
                        {% if projects %}
                            {% for project in projects %}
                                    <div class="card {% if project.client_id == current_user.id %}owner{% endif %} {{ project.academic_year }}">
                                        {% if project.client_id == current_user.id %}
                                            <a id="{{ project.id }}-link" href="{{url_for('staff.my_projects') }}">
                                        {% else %}
                                            <a id="{{ project.id }}-link" href="{{url_for('staff.project', id=project.id) }}">
                                        {% endif %}
                                            <div class="card-header">
                                                {{ project.title }}
                                            </div>
                                            <div class="card-body">
                                                {% if project.client.is_student %}
                                                    Student project
                                                    {% if project.client.company_id is not none %}
                                                        <br>
                                                        ({{ project.client.company.name }})
                                                    {% endif %}
                                                {% else %}
                                                    {{ project.client.company.name }}
                                                {% endif %}
                                                <br/>
                                                {% for skill in project.skills_required %}
                                                    {% if loop.index > 1 %}
                                                    ,
                                                    {% endif %}
                                                    {{ skill.skill_required.name }}
                                                {% endfor %}
                                            </div>
                                        </a>
                                        <div class="card-footer">
                                            <span class="badge {{ project.status.name }}">{{ project.status.name }}</span>
                                            {% if project.status.name != 'Taken' %}
                                                <div class="right-control">
                                                    {% for interest in project.notes_of_interest %}
                                                        {% if interest.user_id == current_user.id %}
                                                            <a href="{{url_for('staff.project', id=project.id) }}" data-toggle="popover"
                                                               data-trigger="hover"
                                                               data-html=true
                                                               data-placement="left"
                                                               data-content="You have a note of interest on this project">
                                                                <span class="action-glyph glyphicon glyphicon-star"></span>
                                                            </a>

                                                        {% endif %}
                                                    {% endfor %}
                                                    {% if project.flags | length > 0 %}
                                                        <a href="{{url_for('staff.project', id=project.id) }}" data-toggle="popover"
                                                           data-trigger="hover"
                                                           data-html=true
                                                           data-placement="left"
                                                           data-content="There is active recruitment for this project - click for more information"
                                                            <span class="blink glyphicon glyphicon-flag"></span>
                                                        </a>
                                                    {% endif %}
                                                    {% if bids[project.id]  > 0 %}
                                                        <span class="badge bids">
                                                            {{ bids[project.id]  }}
                                                            {% if bids[project.id] == 1 %}
                                                                bid
                                                            {% else %}
                                                                bids
                                                            {% endif %}
                                                        </span>
                                                    {% endif %}
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                            {% endfor %}
                        {% else %}
                          <div style="text-align: center">
                            <h4> There are currently no projects available. Please check back later. </h4>
                            <hr class="intro-divider">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    {% block footer %} {{  super() }} {% endblock footer%}
{% endblock %}
{% block help %}
    <p>
        This page lists all of the available projects.
    </p>
    <p>
        An icon is displayed to indicate projects where you have made a note of interest. If you want to remove your
    note of interest, click through to the project details.
    </p>
    <p>
        Where someone is actively recruiting a team for a project, a flag icon is displayed. You can click through
    to find out who is recruiting.
    </p>
    <p>
        Clicking on a project takes you to the details screen where you can find out more about the project,
        make a personal note of interest and register a team bid.
    </p>
{% endblock %}