app/student/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectMultipleField, TextAreaField, BooleanField, SelectField
from wtforms.validators import DataRequired, Optional


class ProfileForm(FlaskForm):
    email = StringField('Email', render_kw={'disabled':''}, validators=[DataRequired()])
    username = StringField('Username', render_kw={'disabled':''}, validators=[DataRequired()])
    first_name = StringField('First name', render_kw={'disabled':''}, validators=[DataRequired()])
    last_name = StringField('Last name', render_kw={'disabled':''}, validators=[DataRequired()])
    profile_comment = TextAreaField('Profile comment')
    skills_offered = SelectMultipleField('Skills offered', coerce=int)
    notify_new = BooleanField('Receive email notification of new projects')
    notify_interest = BooleanField('Receive email notification of new notes of interest on projects you are interested in')
    submit = SubmitField('Save')


class FlagForm(FlaskForm):
    message = TextAreaField('Message', validators=[DataRequired()])
    submit = SubmitField('Save')


class ProjectForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    academic_year = SelectField('Academic year')
    overview = TextAreaField('Overview', validators=[DataRequired()])
    deliverables = TextAreaField('Deliverables', validators=[DataRequired()])
    resources = TextAreaField('Resources', validators=[DataRequired()])
    skills_required = SelectMultipleField('Skills required', coerce=int)
    submit = SubmitField('Save')


class TeamForm(FlaskForm):
    comment = TextAreaField('Team profile comment', validators=[DataRequired()])
    vacancies = TextAreaField('Vacancies message')
    matric = StringField('Add team member')
    submit = SubmitField('Save')

app/student/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__)

from . import views

app/student/views.py
from flask import render_template, flash, redirect, url_for, request, abort
from flask_login import current_user, login_required
from collections import Counter

from sqlalchemy import and_, or_, text
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy.sql.expression import case

from jinja2 import Markup
import re

from . import student
from .forms import *
from app.models import *
from app.common import *
import logging
logger = logging.getLogger()



@student.route('/student/projects/list')
@login_required
def projects():
    skill = request.args.get("skill")
    company = request.args.get("company")
    project_domain = Domain.query.filter(Domain.name == 'project').first()
    statuses = Status.query.filter(and_(Status.domain_id == project_domain.id,
                                        or_(Status.name == 'Live',
                                            Status.name == 'Withdrawn',
                                            Status.name == 'Taken',
                                            Status.name == 'Complete'))).with_entities(Status.id)

    accepted = get_status('team', 'Accepted')
    submitted = get_status('team', 'Submitted')
    team_ids = [m.team_id for m in TeamMember.query.filter(TeamMember.user_id == current_user.id).all()]
    accepted_for = [t.project_id for t in Team.query.filter(and_(Team.id.in_(team_ids), Team.status_id == accepted.id))]
    submitted_for = [t.project_id for t in Team.query.filter(and_(Team.id.in_(team_ids), Team.status_id == submitted.id))]

    projects = Project.query.filter(and_(Project.academic_year == session['academic_year'],
                                         or_(Project.status_id.in_(statuses),
                                             Project.client_id == current_user.id))).\
        order_by((Project.client_id == current_user.id).desc()).\
        order_by(Project.title)

    projects = sorted(projects, key=lambda x: (x.id not in accepted_for, x.id not in submitted_for))

    skills = []
    bids = {}
    for project in projects:
        bids[project.id] = len(get_bids(project))
        skills += [(s.skill_required.name, s.skill_required.name) for s in project.skills_required]
    skills = sorted(Counter(skills).items(), key=lambda x: x[0][0].lower())

    companies = []
    companies += [(p.client.company.name, p.client.company.name) for p in projects if p.client.company_id is not None]
    companies = sorted(Counter(companies).items(), key=lambda x: x[0][0].lower())
    return render_template('student/projects/list.html',
                           projects=projects,
                           bids=bids,
                           accepted_for=accepted_for,
                           submitted_for=submitted_for,
                           skills=skills,
                           skill=skill,
                           companies=companies,
                           company=company,
                           title="Projects")


@student.route('/profile/edit', methods=['GET', 'POST'])
@login_required
def profile():
    user = User.query.get(current_user.id)
    form = ProfileForm(obj=user)
    form.skills_offered.choices = [(s.id, s.name) for s in Skill.query.order_by(text('name'))]
    form.skills_offered.data = [s.skill_id for s in user.skills_offered]

    if form.validate_on_submit():
        # Check for javascript injection
        script_pattern = "<\s*script.*>.*<\s*\/\s*script.*>"
        pattern = ".*" + script_pattern
        string_match = re.match(pattern, form.profile_comment.data)
        if string_match:
            user.profile_comment = re.sub(script_pattern, "- SCRIPT REMOVED -", form.profile_comment.data)
            message = user.first_name + " " + user.last_name + " attempted to place a script into their profile"
            security_alert(message)
        else:
            user.profile_comment = form.profile_comment.data
        user.notify_new = form.notify_new.data
        user.notify_interest = form.notify_interest.data
        SkillOffered.query.filter(SkillOffered.user_id==current_user.id).delete()
        for skill in form.skills_offered.raw_data:
            skill_offered = SkillOffered(user_id=current_user.id, skill_id=skill)
            db.session.add(skill_offered)
        db.session.commit()
        flash('Profile updated')
        return redirect(url_for('student.projects'))

    if form.errors:
        for field in form.errors:
            for error in form.errors[field]:
                flash(error, 'error')

    return render_template('student/profile/profile.html', user=user, form=form, title="Edit profile")


@student.route('/project/<int:id>')
@login_required
def project(id):
    parser = MyHTMLParser()
    project = Project.query.get(id)
    interest = Interest.query.filter(and_(Interest.project_id == id, Interest.user_id == current_user.id)).first()
    flag = Flag.query.filter(and_(Flag.project_id == id, Flag.user_id == current_user.id)).first()
    teams = Team.query.filter(Team.project_id == id)
    team_member = TeamMember.query.filter(and_(TeamMember.user_id == current_user.id,
                                               TeamMember.team_id.in_([t.id for t in teams]))).first()
    transitions = Transition.query.filter(Transition.from_status_id == project.status_id, Transition.admin_only == False).all()

    for n in project.notes_of_interest:
        parser.init()
        if n.user.profile_comment:
            parser.feed(n.user.profile_comment)
            n.user.profile_comment = parser.outstring
    return render_template('student/projects/project.html',
                           project=project,
                           interest=interest,
                           flag=flag,
                           team_member=team_member,
                           transitions=transitions,
                           title='View project')


@student.route('/add_project', methods=['GET', 'POST'])
@login_required
def add_project():
    add_project = True

    form = ProjectForm()
    form.skills_required.choices = [(s.id, s.name) for s in Skill.query.order_by(text('name'))]
    project_domain = Domain.query.filter(Domain.name == 'project').first()
    default_status = Status.query.filter(Status.domain_id == project_domain.id,
                                         Status.default_for_domain == True).first()
    form.academic_year.choices = [(y.year, y.year) for y in AcademicYear.query.filter(AcademicYear.end_date > datetime.now()).order_by(text('start_date'))]

    if form.validate_on_submit():
        skills_required = form.skills_required.data
        project = Project(title = form.title.data,
                          client_id = current_user.id,
                          overview = form.overview.data,
                          deliverables = form.deliverables.data,
                          resources = form.resources.data,
                          academic_year = form.academic_year.data,
                          status_id = default_status.id)

        try:
            db.session.add(project)
            db.session.commit()
            db.session.refresh(project)
            if project.id:
                for skill in skills_required:
                    skill_required = SkillRequired(project_id=project.id, skill_id=skill)
                    db.session.add(skill_required)
                db.session.commit()
                logger.info('NEW STUDENT PROJECT: {:d}, {}, {:d}'.format(project.id, project.title, project.client_id))
                flash('You have successfully added a new project.')
                return redirect(url_for('student.projects'))
            else:
                raise RuntimeError

        except RuntimeError:
            flash('An unknown problem occurred while trying to save a new project', 'error')
            logger.error('PROJECT INSERT ERROR: {:d}, {}'.format(project.client_id, project.title))
        except:
            flash('There was a problem saving your project', 'error')

    return render_template('student/projects/edit_project.html', add_project=add_project,
                           form=form, title='Add project')


@student.route('/edit_project/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_project(id):
    add_project = False

    project = Project.query.get_or_404(id)
    check_client(project)

    form = ProjectForm(obj=project)
    form.academic_year.choices = [(y.year, y.year) for y in AcademicYear.query.order_by(text('start_date'))]
    form.skills_required.choices = [(s.id, s.name) for s in Skill.query.order_by(text('name'))]
    form.skills_required.data = [s.skill_id for s in project.skills_required]
    if form.validate_on_submit():
        project.title = form.title.data
        project.overview = form.overview.data
        project.deliverables = form.deliverables.data
        project.resources = form.resources.data
        project.academic_year = form.academic_year.data
        project.updated_date = datetime.now()
        db.session.add(project)
        SkillRequired.query.filter(SkillRequired.project_id==project.id).delete()
        for skill in form.skills_required.raw_data:
            if skill not in [s.skill_id for s in project.skills_required]:
                skill_required = SkillRequired(project_id=project.id, skill_id=skill)
                db.session.add(skill_required)
        db.session.commit()
        flash('You have successfully edited the project.')

        return redirect(url_for('student.projects'))

    return render_template('student/projects/edit_project.html', add_project=add_project,
                           project=project, form=form, title="Edit project")


@student.route('/projects/project_transition/<int:id>/<int:status_id>', methods=['GET', 'POST'])
@login_required
def transition(id, status_id):

    project = Project.query.get_or_404(id)
    check_client(project)

    status = Status.query.get(status_id)
    project.status_id = status.id
    db.session.add(project)

app/templates/student/projects/list.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                <div class="container projects">
                    <div>
                        {% if skill %}
                            {{ skill }}
                        {% else %}
                            <select id="skill-filter">
                                <option value="0">Filter by skill</option>
                                {% for option, count in skills %}
                                    <option value="{{ option[1] }}">{{ option[0] }} ({{ count }})</option>
                                {% endfor %}
                            </select>
                        {% endif %}
                        {% if company %}
                            {{ company }}
                        {% else %}
                            <select id="company-filter">
                                <option value="0">Filter by company</option>
                                {% for option, count in companies %}
                                    <option value="{{ option[1] }}">{{ option[0] }} ({{ count }})</option>
                                {% endfor %}
                            </select>
                        {% endif %}
                    </div>
                        <div class="card-deck">
                            {% if projects %}
                                {% for project in projects %}
                                        <div class="card m-t-2 {% if project.client_id == current_user.id or
                                                                     project.id in accepted_for%}owner{% endif %}">
                                            {% if project.client_id == current_user.id or
                                                  project.status.name == 'Live' or
                                                  project.status.name == 'Taken'  %}
                                                <a id="{{ project.id }}-link" href="{{url_for('student.project', id=project.id) }}">
                                            {% endif %}
                                            <div class="card-header">
                                                {{ project.title }}
                                            </div>
                                            <div class="card-body">
                                                {% if project.client.is_student %}
                                                    Student project
                                                {% else %}
                                                    {{ project.client.company.name }}
                                                {% endif %}
                                                <br/>
                                                {% for skill in project.skills_required %}
                                                    {% if loop.index > 1 %}
                                                    ,
                                                    {% endif %}
                                                    {{ skill.skill_required.name }}
                                                {% endfor %}
                                            </div>
                                            {% if project.status_id == 3 %}
                                                </a>
                                            {% endif %}
                                            <div class="card-footer">
                                                <span class="badge {{ project.status.name }}">{{ project.status.name }}</span>
                                                {% if project.status.name != 'Taken' %}
                                                    <div class="right-control">
                                                        {% for interest in project.notes_of_interest %}
                                                            {% if interest.user_id == current_user.id %}
                                                                <a href="{{url_for('student.project', id=project.id) }}" data-toggle="popover"
                                                                   data-trigger="hover"
                                                                   data-html=true
                                                                   data-placement="left"
                                                                   data-content="You have a note of interest on this project">
                                                                    <span class="action-glyph glyphicon glyphicon-star"></span>
                                                                </a>

                                                            {% endif %}
                                                        {% endfor %}
                                                        {% if project.flags | length > 0 %}
                                                            <a href="{{url_for('student.project', id=project.id) }}" data-toggle="popover"
                                                               data-trigger="hover"
                                                               data-html=true
                                                               data-placement="left"
                                                               data-content="There is active recruitment for this project - click for more information"
                                                                <span class="blink glyphicon glyphicon-flag"></span>
                                                            </a>
                                                        {% endif %}
                                                        {% if project.id in submitted_for %}
                                                            <a href="{{url_for('student.project', id=project.id) }}" data-toggle="popover"
                                                               data-trigger="hover"
                                                               data-html=true
                                                               data-placement="left"
                                                               data-content="Your team is bidding for this project">
                                                                <span class="badge bids">Bidding</span>
                                                            </a>
                                                        {% endif %}
                                                        {% if bids[project.id] > 0 %}
                                                            <span class="badge bids">
                                                                {{ bids[project.id] }}
                                                                {% if bids[project.id] == 1 %}
                                                                    bid
                                                                {% else %}
                                                                    bids
                                                                {% endif %}
                                                            </span>
                                                        {% endif %}
                                                    </div>
                                                {% elif project.id in accepted_for %}
                                                    <a href="{{url_for('student.project', id=project.id) }}" data-toggle="popover"
                                                       data-trigger="hover"
                                                       data-html=true
                                                       data-placement="left"
                                                       data-content="Your team is accepted for this project">
                                                        <span class="badge Accepted">Accepted</span>
                                                    </a>
                                                {% endif %}
                                            </div>
                                        </div>
                                {% endfor %}

                            {% else %}
                              <div style="text-align: center">
                                <h4> There are currently no projects available. Please check back later. </h4>
                                <hr class="intro-divider">
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    {% block footer %} {{  super() }} {% endblock footer%}
{% endblock %}
{% block help %}
    <p>
        This page lists all of the available projects.
    </p>
    <p>
        An icon is displayed to indicate projects where you have made a note of interest. If you want to remove your
    note of interest, click through to the project details.
    </p>
    <p>
        Where someone is actively recruiting a team for a project, a flag icon is displayed. You can click through
    to find out who is recruiting.
    </p>
    <p>
        Clicking on a project takes you to the details screen where you can find out more about the project,
        make a personal note of interest and register a team bid.
    </p>
{% endblock %}

app/templates/student/projects/project.html
{% extends "base.html" %}
{% import 'macros.html' as m %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    {{  super() }}
    <div class="content-section">
     <div class="outer">
        <div class="middle">
          <div class="inner">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8">
                        <h1>{{ project.title }}</h1>
                        <p>
                            {% if project.client.is_student %}
                                <p>Student project</p>
                            {% elif project.client.company.web %}
                                <a href="{{ project.client.company.web }}" target="blank">{{ project.client.company.name }}</a>
                            {% else %}
                                {{ project.client.company.name }}
                            {% endif %}
                            <br/>
                            {% for skill in project.skills_required %}
                                {% if loop.index > 1 %}
                                ,
                                {% endif %}
                                {{ skill.skill_required.name }}
                            {% endfor %}
                        </p>
                        <h3>Overview</h3>
                        <p class="preserve_newlines">{{ project.overview }}</p>
                        <h3>Deliverables</h3>
                        <p class="preserve_newlines">{{ project.deliverables  }}</p>
                        <h3>Resources</h3>
                        <p class="preserve_newlines">{{ project.resources }}</p>
                        <h3>Contact details</h3>
                        {% if project.client.display_name_flag or project.client.display_email_flag or project.client.display_phone_flag %}
                            {% if project.client.display_name_flag %}
                            {{ project.client.first_name }} {{ project.client.last_name }}<br/>
                            {% endif %}
                            {% if project.client.display_email_flag %}<br/>
                            Email: {{ project.client.email }}
                            {% endif %}
                            {% if project.client.display_phone_flag %}<br/>
                            Phone: {{ project.client.telephone }}
                            {% endif %}
                        {% else %}
                            The client will contact you after you form a team and register a bid for the project.<br/><br/>
                        {% endif %}
                        {% if project.client_id == current_user.id %}
                            {% if project.status.name != 'Complete' %}
                                <a class="btn btn-default" href="{{ url_for('student.edit_project', id=project.id) }}">Edit</a>
                            {% endif %}
                            {% for transition in transitions %}
                                {% if transition.from_status_id == project.status_id %}
                                    {{ m.status('project', 'student.transition', project.id, transition)}}
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="col-sm-4">
                        {% if project.status.name == 'Taken' %}
                            <h3>Project is taken</h3>
                            {% if team_member != None %}
                                <a href="{{url_for('student.edit_team', project_id=project.id, id=team_member.team_id) }}" class="btn btn-default">Manage bid</a>
                            {% endif %}
                        {% else %}
                            <h3>Notes of interest</h3>
                            {% if project.notes_of_interest | length == 0 %}
                                <p>No interest yet</p>
                            {% endif %}
                            {% if team_member != None %}
                                <a href="{{url_for('student.edit_team', project_id=project.id, id=team_member.team_id) }}" class="btn btn-default">Manage bid</a>
                            {% elif not interest %}
                                <a href="{{url_for('student.add_interest', id=project.id) }}" class="btn btn-default">Note your interest</a>
                            {% else %}
                                {% if not project.client.is_student or project.client_id == current_user.id %}
                                    <a href="{{url_for('student.create_team', project_id=project.id, id=team_member.team_id) }}" class="btn btn-default">Register team</a>
                                {% endif %}
                                {% if flag %}
                                    <a href="{{url_for('student.edit_flag', id=flag.id) }}" class="btn btn-default">Edit flag</a>
                                {% elif not project.client.is_student or project.client_id == current_user.id %}
                                    <a href="{{url_for('student.set_flag', id=project.id) }}" class="btn btn-default">Set flag</a>
                                {% endif %}
                            {% endif %}
                            <ul class="interest">
                            {% for note in project.notes_of_interest %}
                                <li>
                                    <a href="#" data-toggle="popover"
                                       data-trigger="focus"
                                       data-html=true
                                       data-placement="left"
                                       title="{{note.user.programme.title}}"
                                       data-content="{{note.user.profile_comment}}
                                       <br><br>
                                        {% for skill in note.user.skills_offered %}
                                            {% if loop.index > 1 %}, {% endif %}
                                            {{ skill.skill_offered.name }}
                                        {% endfor %}
                                        <br><br>
                                         <input id='email-address' value='{{ note.user.email }}'>
                                         <a href='#' onclick='copy_email_address();'><span class='large-icon action-glyph glyphicon glyphicon-copy'></span></a> ">
                                        {{ note.user.first_name }} {{ note.user.last_name }} <span class="glyphicon glyphicon-info-sign"></span></span>
                                    </a>
                                    {% if note.user.id == current_user.id and team_member == None and not flag %}
                                        <a href="{{url_for('student.delete_interest', project_id=project.id, id=note.id) }}"
                                           data-toggle="confirmation"
                                           data-title="Delete your note of interest?"
                                        ><span class="action-glyph glyphicon glyphicon-remove-circle"></span></a>
                                    {%  endif %}
                                    {% for flag in project.flags %}
                                        {% if flag.user_id == note.user_id %}

                                            <a href="#" data-toggle="popover"
                                               data-trigger="focus"
                                               data-html=true
                                               data-placement="left"
                                               data-content="{{flag.message}}
                                                <br><br>
                                                 <input id='email-address' value='{{ flag.user.email }}'>
                                                 <a href='#' onclick='copy_email_address();'><span class='large-icon action-glyph glyphicon glyphicon-copy'></span></a> ">
                                                <span class="blink action-glyph glyphicon glyphicon-flag"></span>
                                            </a>
                                        {% endif %}
                                    {% endfor %}
                                </li>
                            {% endfor %}
                        {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% block footer %} {{  super() }} {% endblock footer%}
{% endblock content%}
{% block help %}
    <p>This page allows you to see the details of the project, and to let other students know that you are interested in it.</p>
    <p>You can register a note of interest by clicking the button on the right. This adds your name to the list of interested
       people, and allows other students to see your profile text. To form a team, make contact with other people who have
       registered notes of interest.</p>
    <p>After registering a note of interest, rather than wait for something to happen, you can invite other students to
        contact you by adding a flag. This lets other people know that you are actively forming a team for this project,
        and they are more likely to contact you. When you flag a project, you can also add a message. This is useful,
        for example, if you have two or three people already and you are specifically looking for people with certain skills.</p>
    <p>Notes of interest are just the first stage of the process. To let the client know that you want to bid for the project
       you need to assemble and register a team. You can do this by clicking the <em>Register team</em> button.</p>
    <p>Please note that you cannot delete a note of interest if you are part of a team bidding for this project. If that
    is the case, you must either remove yourself from the team, or delete the whole team first.</p>
{% endblock %}