app/client/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, TextAreaField, SelectField, SelectMultipleField, RadioField
from wtforms.validators import DataRequired, Optional, URL


class ProjectForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    academic_year = SelectField('Academic year')
    overview = TextAreaField('Overview', validators=[DataRequired()])
    deliverables = TextAreaField('Deliverables', validators=[DataRequired()])
    resources = TextAreaField('Resources', validators=[DataRequired()])
    skills_required = SelectMultipleField('Skills required', coerce=int)
    submit = SubmitField('Save')


class ProfileForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    first_name = StringField('First name', validators=[DataRequired()])
    last_name = StringField('Last name', validators=[DataRequired()])
    telephone = StringField('Telephone', validators=[DataRequired()])
    profile_comment = TextAreaField('Comment')
    display_name_flag = BooleanField('Display name to students', default=False)
    display_email_flag = BooleanField('Display email to students', default=False)
    display_phone_flag = BooleanField('Display phone to students', default=False)
    submit = SubmitField('Save')


class ProfileFormWithCompany(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    first_name = StringField('First name', validators=[DataRequired()])
    last_name = StringField('Last name', validators=[DataRequired()])
    company_id = SelectField('Company - NB: For a new company, please complete the details separately under the profile link in the menu')
    telephone = StringField('Telephone', validators=[DataRequired()])
    profile_comment = TextAreaField('Comment')
    display_name_flag = BooleanField('Display name to students', default=False)
    display_email_flag = BooleanField('Display email to students', default=False)
    display_phone_flag = BooleanField('Display phone to students', default=False)
    submit = SubmitField('Save')


class CompanyForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    address = StringField('Address', validators=[DataRequired()])
    city = StringField('City', validators=[DataRequired()])
    post_code = StringField('Post code', validators=[DataRequired()])
    web = StringField('Web address', validators=[Optional(), URL(message='Please enter your web address including the prefix (eg. http:// or https://')], render_kw={"placeholder": "https://"})
    health_policy_flag = RadioField('Do you have a written Health and Safety policy?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    health_policy_link = StringField('Link to H&S policy')
    training_policy_flag = RadioField('Do you have a H&S training policy?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    training_policy_link = StringField('Link to H&S training policy')
    hse_registered = RadioField('Are you registered with the Health and Safety Executive?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    la_registered = RadioField('Are you registered with the local authority environmental health dept?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    insured = RadioField('Do you have public liability insurance?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    student_insured = RadioField('Does the PL policy cover the student(s)?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    company_risk_assessed = RadioField('Have you carried out a workplace risk assessment?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    risks_reviewed = RadioField('Are risks reviewed regularly?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    risks_mitigated = RadioField('Are risk assessment results implemented?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    accident_procedure_flag = RadioField('Do you have a procedure for reporting accidents?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    emergency_procedures_flag = RadioField('Do you have procedures for dealing with emergencies?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    report_student_accidents_flag = RadioField('Will all accidents involving the student be reported to the University?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    report_student_illness_flag = RadioField('Will any student illness attributable to the work be reported to the University?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    data_policy_flag = RadioField('Do you have a data protection policy?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    data_policy_link = StringField('Link to DP policy')
    security_measures_flag = RadioField('Do you have data protection/privacy measures in place?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    ico_registration_number = StringField('What is your registration number with the Information Commissioner\'s Office?')
    data_training_flag = RadioField('Do staff receive regular data protection training?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    security_policy_flag = RadioField('Do you have information security policies in place?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    security_policy_link = StringField('Link to information security policy')
    privacy_notice_flag = RadioField('Is there a staff privacy notice that would cover the student?', choices=[(1,'yes'),(0,'no')], coerce=int, validators=[Optional()])
    data_contact_first_name = StringField('First name')
    data_contact_last_name = StringField('Last name')
    data_contact_position = StringField('Position')
    data_contact_telephone = StringField('Telephone')
    submit = SubmitField('Save')

app/client/__init__.py
from flask import Blueprint

client = Blueprint('client', __name__)

from . import views

app/client/views.py
import logging
logger = logging.getLogger()

from flask import flash, redirect, render_template, url_for, abort
from flask_login import current_user, login_required
from sqlalchemy import and_
from sqlalchemy.sql import text

from . import client
from .forms import *
from app.models import *
from app.common import *


#--------  Profile views ----------#

@client.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = User.query.get(current_user.id)
    company_id = user.company_id
    new_company = user.company.is_new
    if new_company:
        form = ProfileFormWithCompany(obj=user)
        form.company_id.choices = [(user.company_id, user.company.name)] +\
                                  [(c.id, c.name) for c in Company.query.order_by(text('name')) if c.name != user.company.name]

        form.company_id.data = user.company_id
    else:
        form = ProfileForm(obj=user)

    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.telephone = form.telephone.data
        user.display_name_flag = form.display_name_flag.data
        user.display_email_flag = form.display_email_flag.data
        user.display_phone_flag = form.display_phone_flag.data
        try:
            user.company_id = form.company_id.raw_data[0]
        except AttributeError:
            pass
        user.profile_comment = form.profile_comment.data
        db.session.commit()

        if user.company_id != company_id and new_company:
            db.session.expire_all()
            company = Company.query.get(company_id)
            db.session.delete(company)
            db.session.commit()
        flash('Profile updated')
        return redirect(url_for('client.projects'))

    if form.errors:
        for field in form.errors:
            for error in form.errors[field]:
                flash(error, 'error')

    form.email.data = user.email
    form.username.data = user.username
    form.first_name.data = user.first_name
    form.last_name.data = user.last_name
    form.telephone.data = user.telephone
    form.display_name_flag = user.display_name_flag
    form.display_email_flag = user.display_email_flag
    form.display_phone_flag = user.display_phone_flag
    if user.company.is_new:
        form.company_id.data = user.company_id
    form.profile_comment.data = user.profile_comment
    return render_template('client/profile/profile.html', user=user, form=form, title="Update profile")


@client.route('/company', methods=['GET', 'POST'])
@login_required
def company():
    company = Company.query.filter(Company.id == current_user.company_id).first()
    form = CompanyForm(obj=company)

    if form.validate_on_submit():
        company.name = form.name.data
        company.description = form.description.data
        company.address = form.address.data
        company.city = form.city.data
        company.post_code = form.post_code.data
        if len(form.web.data) > 0:
            company.web = form.web.data                             # Avoids duplicate index values where the user has entered an empty string
        company.health_policy_flag = form.health_policy_flag.data
        company.health_policy_link = form.health_policy_link.data
        company.training_policy_flag = form.training_policy_flag.data
        company.training_policy_link = form.training_policy_link.data
        company.hse_registered = form.hse_registered.data
        company.la_registered = form.la_registered.data
        company.insured = form.insured.data
        company.student_insured = form.student_insured.data
        company.company_risk_assessed = form.company_risk_assessed.data
        company.risks_reviewed = form.risks_reviewed.data
        company.risks_mitigated = form.risks_mitigated.data
        company.accident_procedure_flag = form.accident_procedure_flag.data
        company.emergency_procedures_flag = form.emergency_procedures_flag.data
        company.report_student_accidents_flag = form.report_student_accidents_flag.data
        company.report_student_illness_flag = form.report_student_illness_flag.data
        company.data_policy_flag = form.data_policy_flag.data
        company.data_policy_link = form.data_policy_link.data
        company.security_measures_flag = form.security_measures_flag.data
        company.ico_registration_number = form.ico_registration_number.data
        company.data_training_flag = form.data_training_flag.data
        company.security_policy_flag = form.security_policy_flag.data
        company.security_policy_link = form.security_policy_link.data
        company.privacy_notice_flag = form.privacy_notice_flag.data
        company.data_contact_first_name = form.data_contact_first_name.data
        company.data_contact_last_name = form.data_contact_last_name.data
        company.data_contact_position = form.data_contact_position.data
        company.data_contact_telephone = form.data_contact_telephone.data

        db.session.add(company)
        db.session.commit()
        flash('Company details updated')

        return redirect(url_for('client.projects'))

    errors = form.errors
    if len(errors) > 0:
        for key, value in errors.items():
            flash(value[0], 'error')

    return render_template('client/profile/company.html',
                           company=company, form=form, title="Update company details")



#--------  Project views ----------#

@client.route('/projects')
@login_required
def projects():
    projects = Project.query.filter(Project.client_id == current_user.id).all()
    bids = {}
    new = {}
    for project in projects:
        bids[project.id] = len(get_bids(project))
        new[project.id] = len(get_new_teams(project))
    settings = Settings.query.first()
    from_statuses = [p.status_id for p in projects]
    transitions = Transition.query.filter(Transition.from_status_id.in_(from_statuses), Transition.admin_only == False).all()
    return render_template('client/projects/projects.html',
                           projects=projects,
                           academic_year=get_this_year(),
                           bids=bids,
                           new=new,
                           transitions=transitions,
                           title="Projects")


@client.route('/projects/add', methods=['GET', 'POST'])
@login_required
def add_project():
    add_project = True

    form = ProjectForm()
    form.skills_required.choices = [(s.id, s.name) for s in Skill.query.order_by(text('name'))]
    project_domain = Domain.query.filter(Domain.name == 'project').first()
    default_status = Status.query.filter(Status.domain_id == project_domain.id,
                                         Status.default_for_domain == True).first()
    form.academic_year.choices = [(y.year, y.year) for y in AcademicYear.query.filter(AcademicYear.end_date > datetime.now()).order_by(text('start_date'))]

    if form.validate_on_submit():
        skills_required = form.skills_required.data
        project = Project(title = form.title.data,
                          client_id = current_user.id,
                          overview = form.overview.data,
                          deliverables = form.deliverables.data,
                          resources = form.resources.data,
                          academic_year = form.academic_year.data,
                          status_id = default_status.id)

        try:
            db.session.add(project)
            db.session.commit()
            db.session.refresh(project)
            if project.id:
                for skill in skills_required:
                    skill_required = SkillRequired(project_id=project.id, skill_id=skill)
                    db.session.add(skill_required)
                db.session.commit()
                logger.info('NEW CLIENT PROJECT: {:d}, {}, {:d}'.format(project.id, project.title, project.client_id))
                flash('You have successfully added a new project.')
                return redirect(url_for('client.projects'))
            else:
                raise RuntimeError

        except RuntimeError:
            flash('An unknown problem occurred while trying to save a new project', 'error')
            logger.error('PROJECT INSERT ERROR: {:d}, {}'.format(project.client_id, project.title))
        except:
            flash('There was a problem saving your project', 'error')


    return render_template('client/projects/project.html', add_project=add_project,
                           form=form, title='Add project')


@client.route('/projects/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_project(id):
    add_project = False

    project = Project.query.get_or_404(id)
    check_client(project)

    form = ProjectForm(obj=project)
    form.academic_year.choices = [(y.year, y.year) for y in AcademicYear.query.order_by(text('start_date'))]
    form.skills_required.choices = [(s.id, s.name) for s in Skill.query.order_by(text('name'))]
    form.skills_required.data = [s.skill_id for s in project.skills_required]
    if form.validate_on_submit():
        project.title = form.title.data
        project.overview = form.overview.data
        project.deliverables = form.deliverables.data
        project.resources = form.resources.data
        project.academic_year = form.academic_year.data
        project.updated_date = datetime.now()
        db.session.add(project)
        SkillRequired.query.filter(SkillRequired.project_id==project.id).delete()
        for skill in form.skills_required.raw_data:
            if skill not in [s.skill_id for s in project.skills_required]:
                skill_required = SkillRequired(project_id=project.id, skill_id=skill)
                db.session.add(skill_required)
        db.session.commit()
        flash('You have successfully edited the project.')

app/templates/client/projects/new_client.html
<div>
    <div style="text-align: center">
        <h1>Welcome to Projects Exchange</h1>
    </div>
    <br>
    <hr class="intro-divider">
    <p>This site is operated by the School of Computing at Edinburgh Napier University</p>
    <p>Here you can post project briefs for the students completing the Group Project module which takes place between January and April each year.</p>
    <p>To get started quickly, just click the <i>New project</i> link in the menu and fill in the boxes.</p>
    <p>Please remember to update your company profile information.</p>
    <br/>
    <p>Each page of the site has help informaton available which you can access by clicking <i>Help</i> in the menu.</p>
    <p>After you have saved a new project, it goes through a checking process before it is visible to the students. The details will be reviewed by a member of academic staff who may discuss some changes with you.</p>
    <p>For further informaton, you can use the <i>FAQ</i> link at the foot of the page, or use the <i>Contact</i> link to send us a message.</p>
    <hr class="intro-divider">
</div>

app/templates/client/projects/project.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    {{  super() }}
    <div class="content-section">
     <div class="outer">
        <div class="middle">
          <div class="inner">
            <div class="center">
                <h1>{{title}}</h1>
                <br/>
                {{ wtf.quick_form(form) }}
                {%  if not add_project %}
                    <div id="date_info">
                    Created: {{ project.created_date }}<br/>
                    Last updated: {{ project.updated_date }}
                    </div>
                {%  endif %}
            </div>
          </div>
        </div>
      </div>
    {% block footer %} {{  super() }} {% endblock footer%}
    </div>
{% endblock content%}
{% block help %}
    <p>There are six pieces of information required in a project brief:</p>
    <ul>
    <li>The <em>Title</em> is a one-line summary of the project used to identify the project easily.</li>
    <li>The <em>Academic year</em> is selected from a drop-down list.</li>
    <li>The <em>Overview</em> is a longer description of the project. Students rely on this to form their ideas about
        what the project involves. This section should include the goals, type of activity and the technology to be
        used (if known). You should also highlight the attractive features of the project here.
    </li>
    <li>The <em>Deliverables</em> section lists the expected results from the project. Here, it is good to be specific:
        if you are expecting a piece of software that should be clearly stated. Other deliverables could include reports,
        design documentation, graphical assets, etc.
    </li>
    <li>The <em>Resources available</em> is another list, this time detailing what you can provide to the team to help
        get the work done. This varies enormously from one project to another, and could include software or hardware
        resources, workspace, documentation, etc. It is also a good idea to be specific about how much of your time
        the students can expect to benefit from.
    </li>
    <li>The <em>Skills required</em> section lets you choose skills from a list. To pick more than one, use CTRL-Click
        on a PC and Command-Click on a Mac. If you do not have a clear idea of the skills your project may require,
        just choose something generic and a member of academic staff will be able to suggest something more specific.
    </li>
    </ul>
    <p>Once your project brief has been saved, it will be reviewed by a member of academic staff who will discuss any
    issues with you. Changes may be needed, for example, if the scope of the project is too broad, or if there is
    anything that the students may not understand clearly. Staff have extensive experience of preparing instructions
    for students and are in a good position to help make your project brief accessible.
    </p>
    <p>
    After your project is submitted, it is not immediately visible to students. This is to allow an opportunity to
    discuss the details and make any amendments that may be needed.
    </p>
{% endblock %}

app/templates/client/projects/projects.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% import 'macros.html' as m %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
            <div class="center">
                <br/>
                {% if projects %}
                    <div class="card">
                        <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs">
                        {% for project in projects %}
                              <li class="nav-item">
                                <a class="nav-link active" id="{{ project.id }}-tab" data-toggle="tab" href="#{{ project.id }}"
                                   role="tab" aria-controls="home" aria-selected="true" aria-expanded="true">Project {{ loop.index }}</a>
                              </li>
                        {% endfor %}
                        </ul>
                        </div>
                        <div class="card-body">
                            <div class="tab-content" id="myTabContent">
                                {% for project in projects %}
                                    {% if loop.first %}
                                        <div class="tab-pane fade active in" id="{{project.id}}" role="tabpanel" aria-labelledby="{{project.id}}-tab">
                                    {% else %}
                                        <div class="tab-pane fade" id="{{project.id}}" role="tabpanel" aria-labelledby="{{project.id}}-tab">
                                    {% endif %}

                                        <h4>{{ project.title }}</h4>
                                        <p class="info-text">Academic year: {{ project.academic_year }}      Created: {{ project.created_date }}</p>
                                        <p>
                                            {% if project.status.name != 'Complete' %}
                                                <a href="#" class="action-link" data-toggle="popover"
                                                   data-trigger="focus"
                                                   data-html=true
                                                   data-placement="right"
                                                   title="Project stats"
                                                   data-content="{{project.notes_of_interest | length}} {% if project.notes_of_interest | length == 1 %}Note{% else %}Notes{% endif %} of interest <br>
                                                       {{ project.flags | length }} {% if project.flags | length == 1 %}Flag{% else %}Flags{% endif %} <br>
                                                       {{ new[project.id] }} New {% if new[project.id] == 1 %}team{% else %}teams{% endif %} <br>
                                                       {{ bids[project.id] }} {% if bids[project.id] == 1 %}Bid{% else %}Bids{% endif %} <br><br>
                                                       <em>Notes of interest</em> show how many students are thinking about your project. Students express interest in
                                                       several projects, and so this in not an exact measure.
                                                       Notes are removed when a student joins a team for the project, or is accepted on another
                                                       project.<br><br>
                                                       <em>Flags</em> show whether anyone is actively recruiting a team for your project.<br><br>
                                                       <em>New teams</em> are those which do not yet have enough members to make a formal bid. <br><br>
                                                       <em>Bids</em> include those which have been <em>submitted</em>, <em>shortlisted</em>, or <em>accepted</em>.
                                                        ">
                                                    <span class="action-glyph glyphicon glyphicon-stats"></span>
                                                </a>
                                            {% endif %}
                                            <span class="badge {{ project.status.name }}">{{ project.status.name }}</span>: {{ project.status.description }}
                                        </p>
                                        <h5>Overview </h5>
                                        <p class="preserve_newlines">{{ project.overview }}</p>
                                        <h5>Deliverables </h5>
                                        <p class="preserve_newlines">{{ project.deliverables }}</p>
                                        <h5>Resources </h5>
                                        <p class="preserve_newlines">{{ project.resources }}</p>
                                        <h5>Skills required </h5>
                                            {% for skill in project.skills_required %}
                                                {{ skill.skill_required.name }}<br/>
                                            {%  endfor %}

                                        <br/><br/>

                                        {% if project.status.name != 'Complete' %}
                                            {% if bids[project.id] > 0 %}
                                                <a href="{{ url_for('client.bids', id=project.id) }}" class="btn btn-default">
                                                    {% if project.status.name == 'Taken' %}
                                                        {% if bids[project.id] > 1 %}
                                                            Teams
                                                        {% else %}
                                                            Team
                                                        {% endif %}
                                                    {% else %}
                                                        Bids <span class="badge badge-info">{{ bids[project.id] }}</span>
                                                    {% endif %}
                                                </a>
                                            {% else %}
                                                <button type="button" class="btn btn-default disabled">
                                                    Bids</span>
                                                </button>
                                            {% endif %}
                                            <a href="{{url_for('client.edit_project', id=project.id) }}" class="btn btn-default">Edit</a>
                                        {% endif %}
                                        {% for transition in transitions %}
                                            {% if transition.from_status_id == project.status_id %}
                                                {{ m.status('project', 'client.transition', project.id, transition)}}
                                            {% endif %}
                                        {% endfor %}
                                        {% if project.status.name == 'Old' or project.status.name == 'Withdrawn' %}
                                            <a href="{{ url_for('client.duplicate', id=project.id) }}" class="btn btn-default">
                                                Copy for {{ academic_year.year }}
                                            </a>
                                        {% endif %}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        </div>
                    </div>
                {% else %}
                  <div>
                    {% include 'client/projects/new_client.html' %}
                {% endif %}
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
    {% block footer %} {{  super() }} {% endblock footer%}
{% endblock %}
{% block help %}
    <p>
        This page gives you access to all of the features you need to manage your projects which are visible in the
        central tabbed area. When your project is visible to students, you can check the level of interest by clicking
        the <em>Project stats</em> icon <span class="glyphicon glyphicon-stats"></span> . When checking this information,
        please remember that students will also be signalling their interest in other projects on the list. The numbers
        are therefore not an exact reflection of the popularity of your project, and should only be used as an indication.
    </p>
    <p>
        The menu items are self-explanatory and lead to other pages where further help information is available.
    </p>
        The <em>Bids</em> button shows how many teams are bidding on each project. Clicking it takes you to a page where
        you can see the details of the bids and respond to them.
    </p>
    <p>
        The other buttons below a project let you change its status. The available statuses are listed below:
        <ul>
            <li><em>New</em>: The project is being checked by academic staff and is not yet visible to the students.</li>
            <li><em>Live</em>: The project is visible to the students and teams can make bids.
                A project can only be moved to <em>Live</em> by a member of academic staff. Another requirement is
                that you have completed your profile.
            </li>
            <li><em>Protected</em>: A project in this status is only visible to selected students. This can be used,
                for example, when you have already decided on a team and you do not wish the project to be available
                for other bids.
            </li>
            <li><em>Withdrawn</em>: A project in this status is no longer visible to students. This would be appropriate,
                for example, when you change your mind or a project is no longer viable.
            </li>
            <li><em>Relisted</em>: A <em>Withdrawn</em> project can be relisted. This status requires checking by a member of
                academic staff just like a <em>New</em> project. A project can also be relisted if an accepted team withdraws.
            </li>
            <li><em>Complete</em>: Once the project is over and you have taken delivery of the results,
                the project's status should be updated to <em>Complete</em>.
            </li>

        </ul>
    </p>
{% endblock %}